### PR TITLE
Task 7

### PR DESCRIPTION
**Pull request by Vladlan**
* **1** - **authorization-service** is added to the repo, has correct **basicAuthorizer** lambda and correct **serverless.ts** file
* **3** - **import-service** serverless.yaml file has authorizer configuration for the **importProductsFile** lambda. Request to the **importProductsFile** lambda should work only with correct **authorization_token** being decoded and checked by **basicAuthorizer** lambda. Response should be in 403 HTTP status if access is denied for this user (invalid **authorization_token**) and in 401 HTTP status if Authorization header is not provided.
* **5** - update client application to send Authorization: Basic **authorization_token** header on import. Client should get **authorization_token** value from browser localStorage https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage
**authorization_token** = localStorage.getItem('**authorization_token**')
 
## Additional (optional) tasks
---
* **+1** - Client application should display alerts for the responses in 401 and 403 HTTP statuses. This behavior should be added to the **nodejs-aws-fe-main/src/index.tsx** file

**Final mark: 6/6**

FE link: https://d32m2krhvblmxn.cloudfront.net
FE PR: https://github.com/Vladlan/nodejs-aws-fe/pull/5
BE link: https://xherne2245.execute-api.eu-west-1.amazonaws.com/dev/import?csvFileName=products-aws-task.csv

### CODE REVIEW

**Comment by valakar** [comment]
Hi @Vladlan , in my opinion sending **Authorization: Basic null** is not a best way - you could just skip this header if no token provided
image

**Review by sleepwalky — APPROVED** [review]
a bit noisy PR 🙂

**Comment by Vladlan** [comment]
@sleepwalky 
Agree (after I added prettier and eslint), but you could check it by commits.

**Comment by Vladlan** [comment]
@valakar agree. Thanks!

**Pull request merged**
